// <auto-generated />
using System;
using Lombard.Domain.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lombard.Migrations
{
    [DbContext(typeof(LombardContext))]
    [Migration("20220421071709_types")]
    partial class types
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lombard.Domain.Entities.Act", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IndividualDebtorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LegalDebtorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<double>("TotalGoldCount")
                        .HasColumnType("float");

                    b.Property<double>("TotalGoldLikvidPrice")
                        .HasColumnType("float");

                    b.Property<double>("TotalGoldMarketPrice")
                        .HasColumnType("float");

                    b.Property<double>("TotalGoldNetWeight")
                        .HasColumnType("float");

                    b.Property<double>("TotalGoldWeight")
                        .HasColumnType("float");

                    b.Property<double>("TotalJewelsWeight")
                        .HasColumnType("float");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IndividualDebtorId");

                    b.HasIndex("LegalDebtorId");

                    b.HasIndex("ParentId");

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.ActIndividualContract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ActId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("IndividualContractId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("IndividualContractId");

                    b.ToTable("ActIndividualContracts");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Bail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CorporativeContractID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evaluator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IndividualContractID")
                        .HasColumnType("bigint");

                    b.Property<long?>("IndividualDebtorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LegalDebtorId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorporativeContractID");

                    b.HasIndex("IndividualContractID");

                    b.HasIndex("IndividualDebtorId");

                    b.HasIndex("LegalDebtorId");

                    b.ToTable("Bails");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Bank", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrespondentAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForPrint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("SWIFT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VOEN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.BankAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BankId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IndividualDebtorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsMainAccount")
                        .HasColumnType("bit");

                    b.Property<long?>("LegalDebtorId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("IndividualDebtorId");

                    b.HasIndex("LegalDebtorId");

                    b.ToTable("BankAccount");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.BusinessArea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BusinessArea");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.CorporativeContract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AnnualPercentage")
                        .HasColumnType("float");

                    b.Property<decimal>("AnnuityAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BackOfficeApprover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BackOfficeConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CalculationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Comission")
                        .HasColumnType("float");

                    b.Property<decimal>("ComissionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ContractNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContractTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<double>("CreditLimit")
                        .HasColumnType("float");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionMaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountedMonths")
                        .HasColumnType("int");

                    b.Property<string>("Expert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FIFD")
                        .HasColumnType("float");

                    b.Property<DateTime>("GivingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Guarantors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IndividualDebtorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsComissionFull")
                        .HasColumnType("bit");

                    b.Property<long?>("LegalDebtorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LoanEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoanExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanPeriod")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Percentage")
                        .HasColumnType("float");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("RefusalReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IndividualDebtorId");

                    b.HasIndex("LegalDebtorId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SourceId");

                    b.ToTable("CorporativeContracts");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.CreditStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("CreditStatuses");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IndividualDebtorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LegalDebtorId")
                        .HasColumnType("bigint");

                    b.Property<string>("MobileAdditional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("RelationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RelationTypeId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Salary")
                        .HasColumnType("float");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPosition")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndividualDebtorId");

                    b.HasIndex("LegalDebtorId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Gold", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ActId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("GoldTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("HallmarkId")
                        .HasColumnType("bigint");

                    b.Property<int>("ItemsCount")
                        .HasColumnType("int");

                    b.Property<double>("JewelWeight")
                        .HasColumnType("float");

                    b.Property<double>("LikvidPrice")
                        .HasColumnType("float");

                    b.Property<double>("MarketPrice")
                        .HasColumnType("float");

                    b.Property<double>("NetWeight")
                        .HasColumnType("float");

                    b.Property<double>("OneGramLikvidPrice")
                        .HasColumnType("float");

                    b.Property<double>("OneGramStorePrice")
                        .HasColumnType("float");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<double>("TotalWeight")
                        .HasColumnType("float");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActId");

                    b.HasIndex("GoldTypeId");

                    b.HasIndex("HallmarkId");

                    b.ToTable("Golds");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.GoldType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("GoldTypes");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.GuaranterContract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CorporativeContractId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IndividualContractId")
                        .HasColumnType("bigint");

                    b.Property<long?>("IndividualDebtorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LegalDebtorId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorporativeContractId");

                    b.HasIndex("IndividualContractId");

                    b.HasIndex("IndividualDebtorId");

                    b.HasIndex("LegalDebtorId");

                    b.ToTable("GuaranterContracts");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Hallmark", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LikvidPriceOfOneGram")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MarketPriceOfOneGram")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Hallmarks");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.IndividualContract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AnnualPercentage")
                        .HasColumnType("float");

                    b.Property<decimal>("AnnuityAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BackOfficeApprover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BackOfficeConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CalculationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Comission")
                        .HasColumnType("float");

                    b.Property<decimal>("ComissionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ContractNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ContractTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DecisionMaker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountedMonths")
                        .HasColumnType("int");

                    b.Property<string>("Expert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FIFD")
                        .HasColumnType("float");

                    b.Property<DateTime>("GivingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Guarantors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IndividualDebtorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsComissionFull")
                        .HasColumnType("bit");

                    b.Property<long?>("LegalDebtorId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LoanEffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LoanExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoanPeriod")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Percentage")
                        .HasColumnType("float");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("RefusalReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IndividualDebtorId");

                    b.HasIndex("LegalDebtorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SourceId");

                    b.ToTable("IndividualContracts");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.IndividualDebtor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Citizenship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentLivingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IDFincode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IDGiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IDOrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<string>("IsResident")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarialStatuses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileAdditional1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileAdditional2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileAdditional3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileAdditional4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneAdditional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VOEN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IndividualDebtors");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Experience")
                        .HasColumnType("float");

                    b.Property<long?>("IndividualDebtorId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VOEN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndividualDebtorId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.LegalDebtor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentLivingAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadAccountant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsResident")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileAdditional1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileAdditional2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileAdditional3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileAdditional4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneAdditional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("RegisteredAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VOEN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LegalDebtors");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.PaymentSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CorporativeContractID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IndividualContractID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InitialRemainder")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LastRemainder")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MainDebtPayment")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PercentageDebtPayment")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorporativeContractID")
                        .IsUnique()
                        .HasFilter("[CorporativeContractID] IS NOT NULL");

                    b.HasIndex("IndividualContractID")
                        .IsUnique()
                        .HasFilter("[IndividualContractID] IS NOT NULL");

                    b.ToTable("PaymentSchedule");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Pledge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalPledgeContractNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExtractionContractId")
                        .HasColumnType("bigint");

                    b.Property<double?>("LikvidPrice")
                        .HasColumnType("float");

                    b.Property<double?>("NetWeight")
                        .HasColumnType("float");

                    b.Property<double?>("NetWeight583_585")
                        .HasColumnType("float");

                    b.Property<double?>("NetWeight_375")
                        .HasColumnType("float");

                    b.Property<double?>("NetWeight_500")
                        .HasColumnType("float");

                    b.Property<double?>("NetWeight_750")
                        .HasColumnType("float");

                    b.Property<double?>("NetWeight_875")
                        .HasColumnType("float");

                    b.Property<double?>("NetWeight_916")
                        .HasColumnType("float");

                    b.Property<double?>("NetWeight_999")
                        .HasColumnType("float");

                    b.Property<string>("PackageNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PledgeContractId")
                        .HasColumnType("bigint");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<double?>("StorePrice")
                        .HasColumnType("float");

                    b.Property<double?>("TotalWeight")
                        .HasColumnType("float");

                    b.Property<double?>("TotalWeight583_585")
                        .HasColumnType("float");

                    b.Property<double?>("TotalWeight_375")
                        .HasColumnType("float");

                    b.Property<double?>("TotalWeight_500")
                        .HasColumnType("float");

                    b.Property<double?>("TotalWeight_750")
                        .HasColumnType("float");

                    b.Property<double?>("TotalWeight_875")
                        .HasColumnType("float");

                    b.Property<double?>("TotalWeight_916")
                        .HasColumnType("float");

                    b.Property<double?>("TotalWeight_999")
                        .HasColumnType("float");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PledgeContractId");

                    b.ToTable("Pledges");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.PledgeContract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActType")
                        .HasColumnType("int");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CorporativeContractId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<double>("TotalGoldLikvidPrice")
                        .HasColumnType("float");

                    b.Property<double>("TotalGoldMarketPrice")
                        .HasColumnType("float");

                    b.Property<double>("TotalGoldNetWeight")
                        .HasColumnType("float");

                    b.Property<double>("TotalGoldWeight")
                        .HasColumnType("float");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorporativeContractId");

                    b.ToTable("PledgeContracts");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoanAssignment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LocalCardAvailability")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PenaltyPercentage")
                        .HasColumnType("float");

                    b.Property<string>("ProductPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.ProductGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFiveWorkdaysSchedule")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.RefusalReason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RefusalReasons");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.RelationType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RelationTypes");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Source", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Act", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.IndividualDebtor", "IndividualDebtor")
                        .WithMany("Acts")
                        .HasForeignKey("IndividualDebtorId");

                    b.HasOne("Lombard.Domain.Entities.LegalDebtor", "LegalDebtor")
                        .WithMany("Acts")
                        .HasForeignKey("LegalDebtorId");

                    b.HasOne("Lombard.Domain.Entities.Act", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.ActIndividualContract", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.Act", "Act")
                        .WithMany("ActIndividualContracts")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lombard.Domain.Entities.IndividualContract", "IndividualContract")
                        .WithMany("ActIndividualContracts")
                        .HasForeignKey("IndividualContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Bail", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.CorporativeContract", "CorporativeContracts")
                        .WithMany()
                        .HasForeignKey("CorporativeContractID");

                    b.HasOne("Lombard.Domain.Entities.IndividualContract", "IndividualContracts")
                        .WithMany()
                        .HasForeignKey("IndividualContractID");

                    b.HasOne("Lombard.Domain.Entities.IndividualDebtor", "IndividualDebtor")
                        .WithMany()
                        .HasForeignKey("IndividualDebtorId");

                    b.HasOne("Lombard.Domain.Entities.LegalDebtor", "LegalDebtor")
                        .WithMany()
                        .HasForeignKey("LegalDebtorId");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.BankAccount", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.Bank", "Bank")
                        .WithMany("BankAccounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lombard.Domain.Entities.IndividualDebtor", "IndividualDebtor")
                        .WithMany("BankAccounts")
                        .HasForeignKey("IndividualDebtorId");

                    b.HasOne("Lombard.Domain.Entities.LegalDebtor", "LegalDebtor")
                        .WithMany("BankAccounts")
                        .HasForeignKey("LegalDebtorId");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.CorporativeContract", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.IndividualDebtor", "IndividualDebtor")
                        .WithMany("CorporativeContracts")
                        .HasForeignKey("IndividualDebtorId");

                    b.HasOne("Lombard.Domain.Entities.LegalDebtor", "LegalDebtor")
                        .WithMany("CorporativeContracts")
                        .HasForeignKey("LegalDebtorId");

                    b.HasOne("Lombard.Domain.Entities.CorporativeContract", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("Lombard.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lombard.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.FamilyMember", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.IndividualDebtor", "IndividualDebtor")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("IndividualDebtorId");

                    b.HasOne("Lombard.Domain.Entities.LegalDebtor", "LegalDebtor")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("LegalDebtorId");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Gold", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.Act", "Act")
                        .WithMany("Golds")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lombard.Domain.Entities.GoldType", "GoldType")
                        .WithMany()
                        .HasForeignKey("GoldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lombard.Domain.Entities.Hallmark", "Hallmark")
                        .WithMany()
                        .HasForeignKey("HallmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lombard.Domain.Entities.GuaranterContract", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.CorporativeContract", "CorporativeContract")
                        .WithMany("GuaranterContract")
                        .HasForeignKey("CorporativeContractId");

                    b.HasOne("Lombard.Domain.Entities.IndividualContract", "IndividualContract")
                        .WithMany("GuaranterIndividualContract")
                        .HasForeignKey("IndividualContractId");

                    b.HasOne("Lombard.Domain.Entities.IndividualDebtor", "IndividualDebtor")
                        .WithMany("GuaranterIndividualContracts")
                        .HasForeignKey("IndividualDebtorId");

                    b.HasOne("Lombard.Domain.Entities.LegalDebtor", "LegalDebtor")
                        .WithMany("GuaranterIndividualContracts")
                        .HasForeignKey("LegalDebtorId");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.IndividualContract", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.IndividualDebtor", "IndividualDebtor")
                        .WithMany("IndividualContracts")
                        .HasForeignKey("IndividualDebtorId");

                    b.HasOne("Lombard.Domain.Entities.LegalDebtor", "LegalDebtor")
                        .WithMany("IndividualContracts")
                        .HasForeignKey("LegalDebtorId");

                    b.HasOne("Lombard.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lombard.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Job", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.IndividualDebtor", "IndividualDebtor")
                        .WithMany("Jobs")
                        .HasForeignKey("IndividualDebtorId");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.PaymentSchedule", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.CorporativeContract", "CorporativeContracts")
                        .WithOne("PaymentSchedule")
                        .HasForeignKey("Lombard.Domain.Entities.PaymentSchedule", "CorporativeContractID");

                    b.HasOne("Lombard.Domain.Entities.IndividualContract", "IndividualContracts")
                        .WithOne("PaymentSchedule")
                        .HasForeignKey("Lombard.Domain.Entities.PaymentSchedule", "IndividualContractID");
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Pledge", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.PledgeContract", "PledgeContract")
                        .WithMany("PledgeList")
                        .HasForeignKey("PledgeContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lombard.Domain.Entities.PledgeContract", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.CorporativeContract", "CorporativeContract")
                        .WithMany("PledgeContracts")
                        .HasForeignKey("CorporativeContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lombard.Domain.Entities.Product", b =>
                {
                    b.HasOne("Lombard.Domain.Entities.ProductGroup", "Group")
                        .WithMany("Products")
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
